apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: inventory-app
      restartPolicy: Always
      initContainers:
        - name: wait-for-inventory-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 3 inventory-db 5432; do echo waiting for inventory-db; sleep 5; done;",
            ]
      containers:
        - name: inventory-app
          image: orchestratorproject/inventory-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: INVENTORY_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_DB_HOST
            - name: INVENTORY_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_DB_PORT
            - name: INVENTORY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_DB_NAME
            - name: INVENTORY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_DB_USER
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app
spec:
  selector:
    app: inventory-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
