apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  serviceName: inventory-db
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: ${GITLAB_REGISTRY_URL}/root/inventory-app/inventory-db:${CI_COMMIT_SHORT_SHA}
          ports:
            - containerPort: 5432
          env:
            # PostgreSQL admin credentials
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "postgres"
            # Original variables for app compatibility
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: inventory-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: inventory-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
        storageClassName: local-storage
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  clusterIP: None
  selector:
    app: inventory-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-vol
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/inventory
  claimRef:
    namespace: default
    name: inventory-db-data-inventory-db-0
