apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: inventory-app
  annotations:
    note: generated

resources:
  - inventory-app.yaml
  - inventory-db.yaml
