apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: inventory-secrets
    envs:
      - ../.env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: inventory-app
  annotations:
    note: generated

resources:
  - inventory-app.yaml
  - inventory-db.yaml
