services:
  gitlab:
    image: gitlab/gitlab-ee:17.11.1-ee.0
    container_name: code-keeper-gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_ssh_host'] = '${GITLAB_SSH_HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Enable the container registry
        registry_external_url '${GITLAB_EXTERNAL_URL}:5050'
        registry['enable'] = true
        registry['http_enabled'] = true
        registry['http_address'] = '0.0.0.0:5050'
        registry['https_enabled'] = false
        # Configure GitLab to use less memory if needed
        postgresql['shared_buffers'] = "256MB"
    ports:
      - '80:80'
      - '8443:443'
      - '2222:22'
      - '5050:5050'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - '/var/run/docker.sock:/var/run/docker.sock'
    shm_size: '256m'
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './runners/config:/etc/gitlab-runner' 
    networks:
      - gitlab-network
    privileged: true

networks:
  gitlab-network:
    driver: bridge