apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-billing-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 3 billing-db 5432; do echo waiting for billing-db; sleep 5; done",
            ]
      containers:
        - name: billing-app
          image: orchestratorproject/billing-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BILLING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: BILLING_DB_HOST
            - name: BILLING_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: BILLING_DB_PORT
            - name: BILLING_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: BILLING_DB_NAME
            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: BILLING_DB_USER
            - name: BILLING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: BILLING_DB_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_API_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_API_URL
            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: RABBITMQ_QUEUE
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---

