apiVersion: v1
kind: Service
metadata:
  name: billing-db
  labels:
    app: billing-db
spec:
  selector:
    app: billing-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
spec:
  serviceName: billing-db
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: "${DOCKER_HUB_REPO}/billing-db:${CI_COMMIT_SHORT_SHA}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: billing-db-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: billing-db-data
          emptyDir: {}
