apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: billing-app
  annotations:
    note: generated

resources:
  - billing-app.yaml
  - billing-db.yaml
