apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: api-gateway-app
      restartPolicy: Always
      initContainers:
        - name: wait-for-queue
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 3 billing-queue 5672; do echo waiting for billing-queue; sleep 5; done;",
            ]
      containers:
        - name: api-gateway
          image: orchestratorproject/api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: GATEWAY_HOST
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: GATEWAY_HOST
            - name: GATEWAY_PORT
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: GATEWAY_PORT
            - name: INVENTORY_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: INVENTORY_URL
            - name: RABBITMQ_API_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: RABBITMQ_API_URL
            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: RABBITMQ_QUEUE
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app
spec:
  type: ClusterIP
  selector:
    app: api-gateway-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
