services:
  billing-db:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.billing-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: billing-db
    volumes:
      - billing-db-volume:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - billing-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  billing-app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.billing-app
    environment:
      DB_HOST: billing-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      HOST: ${HOST}
    container_name: billing-app
    ports:
      - "${PORT:-8081}:8081"
    depends_on:
      billing-db:
        condition: service_healthy
    networks:
      - billing-network

networks:
  billing-network:
    driver: bridge

volumes:
  billing-db-volume:
    driver: local