services:
  inventory-db:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.inventory-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: inventory-db
    volumes:
      - inventory-db-volume:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.inventory-app
    environment:
      DB_HOST: inventory-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      HOST: ${HOST}
    container_name: inventory-app
    ports:
      - "${PORT}:8080"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  inventory-db-volume:
    driver: local